package com.jayu.allinonenews.utils

class Constants{

    val gs = "Gujarat Samachar"
    val db = "Divya Bhaskar"
    val asmita = "ABP Asmita"
    val topStories = "Top Stories"
    val scienceAndTechnology = "Science & Technology"
    val relationship = "Relationship"
    val lifestyleAndFashion = "Lifestyle & Fashion"
    val health = "Health"
    val astro = "Astro"
    val nriNews = "NRI News"
    val entertainment = "Entertainment"
    val sports = "Sports"
    val business = "Business"
    val international = "International"
    val national = "National"
    val gujarat = "Gujarat"
    val uttarGujarat = "Uttar Gujarat"
    val madhyaGujarat = "Madhya Gujarat"
    val saurashtra = "Saurashtra"
    val kutch = "Kutch"
    val daxinGujarat = "Daxin Gujarat"
    val ahmedabad = "Ahmedabad"
    val baroda = "Baroda"
    val surat = "Surat"
    val rajkot = "Rajkot"
    val bhavnagar = "Bhavnagar"
    val bhuj = "Bhuj"
    val kheda = "Kheda - Anand"
    val gandhinagar = "Gandhinagar"
    val northGujarat = "North Gujarat"
    val nrg = "NRG"
}