package com.jayu.allinonenews.utils

class StringConstants{

    val gs = "Gujarat Samachar"
    val db = "Divya Bhaskar"
    val asmita = "ABP Asmita"
    val news18 = "News18 Gujarati"

    val topStories = "Top Stories"
    val scienceAndTechnology = "Science & Technology"
    val relationship = "Relationship"
    val lifestyleAndFashion = "Lifestyle & Fashion"
    val lifestyle = "Lifestyle"
    val health = "Health"
    val astro = "Astro"
    val nriNews = "NRI News"
    val entertainment = "Entertainment"
    val sports = "Sports"
    val business = "Business"
    val international = "International"
    val national = "National"
    val gujarat = "Gujarat"
    val uttarGujarat = "Uttar Gujarat"
    val madhyaGujarat = "Madhya Gujarat"
    val saurashtra = "Saurashtra"
    val kutch = "Kutch"
    val daxinGujarat = "Daxin Gujarat"
    val ahmedabad = "Ahmedabad"
    val baroda = "Baroda"
    val surat = "Surat"
    val rajkot = "Rajkot"
    val bhavnagar = "Bhavnagar"
    val bhuj = "Bhuj"
    val kheda = "Kheda - Anand"
    val gandhinagar = "Gandhinagar"
    val vadodara = "Vadodara"
    val mehsana = "Mehsana"
    val anand = "Anand"
    val northGujarat = "North Gujarat"
    val nrg = "NRG"
    val home = "Home"
    val asmitaVishesh = "Asmita Vishesh"
    val world = "World"
    val gadgets = "Gadgets"
    val crime = "Crime"
    val dharma = "Dharma"
    val bollywood = "Bollywood"
    val viral = "Viral"
    val events = "Events"
    val covid19 = "Covid19"
    val ajabGajab = "Ajab Gajab"
    val cricket ="Cricket"
    val job = "Job"
    val country = "Country"
    val pressNote = "Press Note"
    val indoChina = "India China Struggle"
    val movies = "Movies"
    val mobileAndTech = "Mobile And Technology"
    val trade = "Trade"
    val nationalInternational = "National-International"
}