package com.jayu.allinonenews.utils

class URLConstants {

    val gsTopStoriesUrl = "https://www.gujaratsamachar.com/rss/top-stories"
    val gsScienceAndTechnologyUrl = "https://www.gujaratsamachar.com/rss/category/science-technology"
    val gsRelationshipUrl = "https://www.gujaratsamachar.com/rss/category/relationship"
    val gsLifestyleAndFashionUrl = "https://www.gujaratsamachar.com/rss/category/lifestyle-fashion"
    val gsHealthUrl = "https://www.gujaratsamachar.com/rss/category/health"
    val gsAstroUrl = "https://www.gujaratsamachar.com/rss/category/astro"
    val gsNriNewsUrl = "https://www.gujaratsamachar.com/rss/category/nri-news"
    val gsEntertainmentUrl = "https://www.gujaratsamachar.com/rss/category/entertainment"
    val gsSportsUrl = "https://www.gujaratsamachar.com/rss/category/sports"
    val gsBusinessUrl = "https://www.gujaratsamachar.com/rss/category/business"
    val gsIinternationalUrl = "https://www.gujaratsamachar.com/rss/category/international"
    val gsNationalUrl = "https://www.gujaratsamachar.com/rss/category/national"
    val gsGujaratUrl = "https://www.gujaratsamachar.com/rss/category/gujarat"
    val gsUttarGujaratUrl = "https://www.gujaratsamachar.com/rss/category/uttar-gujarat"
    val gsMadhyaGujaratUrl = "https://www.gujaratsamachar.com/rss/category/madhya-gujarat"
    val gsSaurashtraUrl = "https://www.gujaratsamachar.com/rss/category/saurashtra"
    val gsKutchUrl = "https://www.gujaratsamachar.com/rss/category/kutch"
    val gsDaxinGujaratUrl = "https://www.gujaratsamachar.com/rss/category/daxin-gujarat"
    val gsAhmedabadUrl = "https://www.gujaratsamachar.com/rss/city/ahmedabad"
    val gsBarodaUrl = "https://www.gujaratsamachar.com/rss/city/baroda"
    val gsSuratUrl = "https://www.gujaratsamachar.com/rss/city/surat"
    val gsRajkotUrl = "https://www.gujaratsamachar.com/rss/city/rajkot"
    val gsBhavnagarUrl = "https://www.gujaratsamachar.com/rss/city/bhavnagar"
    val gsBhujUrl = "https://www.gujaratsamachar.com/rss/city/bhuj"
    val gsKhedaUrl = "https://www.gujaratsamachar.com/rss/city/kheda-anand"
    val gsGandhinagarUrl = "https://www.gujaratsamachar.com/rss/city/gandhinagar"
    val gsNorthGujaratUrl = "https://www.gujaratsamachar.com/rss/city/north-gujarat"
    val dbEntertainmentUrl = "https://www.divyabhaskar.co.in/rss-feed/12042/"
    val dbBusinessUrl = "https://www.divyabhaskar.co.in/rss-feed/969/"
    val dbNationalUrl = "https://www.divyabhaskar.co.in/rss-feed/1037/"
    val dbInternationalUrl = "https://www.divyabhaskar.co.in/rss-feed/1038/"
    val dbSportsUrl = "https://www.divyabhaskar.co.in/rss-feed/970/"
    val dbNRGUrl = "https://www.divyabhaskar.co.in/rss-feed/7453/"

}