package com.jayu.allinonenews.utils

class URLConstants {

    val gsTopStoriesUrl = "https://www.gujaratsamachar.com/rss/top-stories"
    val gsScienceAndTechnologyUrl = "https://www.gujaratsamachar.com/rss/category/science-technology"
    val gsRelationshipUrl = "https://www.gujaratsamachar.com/rss/category/relationship"
    val gsLifestyleAndFashionUrl = "https://www.gujaratsamachar.com/rss/category/lifestyle-fashion"
    val gsHealthUrl = "https://www.gujaratsamachar.com/rss/category/health"
    val gsAstroUrl = "https://www.gujaratsamachar.com/rss/category/astro"
    val gsNriNewsUrl = "https://www.gujaratsamachar.com/rss/category/nri-news"
    val gsEntertainmentUrl = "https://www.gujaratsamachar.com/rss/category/entertainment"
    val gsSportsUrl = "https://www.gujaratsamachar.com/rss/category/sports"
    val gsBusinessUrl = "https://www.gujaratsamachar.com/rss/category/business"
    val gsIinternationalUrl = "https://www.gujaratsamachar.com/rss/category/international"
    val gsNationalUrl = "https://www.gujaratsamachar.com/rss/category/national"
    val gsGujaratUrl = "https://www.gujaratsamachar.com/rss/category/gujarat"
    val gsUttarGujaratUrl = "https://www.gujaratsamachar.com/rss/category/uttar-gujarat"
    val gsMadhyaGujaratUrl = "https://www.gujaratsamachar.com/rss/category/madhya-gujarat"
    val gsSaurashtraUrl = "https://www.gujaratsamachar.com/rss/category/saurashtra"
    val gsKutchUrl = "https://www.gujaratsamachar.com/rss/category/kutch"
    val gsDaxinGujaratUrl = "https://www.gujaratsamachar.com/rss/category/daxin-gujarat"
    val gsAhmedabadUrl = "https://www.gujaratsamachar.com/rss/city/ahmedabad"
    val gsBarodaUrl = "https://www.gujaratsamachar.com/rss/city/baroda"
    val gsSuratUrl = "https://www.gujaratsamachar.com/rss/city/surat"
    val gsRajkotUrl = "https://www.gujaratsamachar.com/rss/city/rajkot"
    val gsBhavnagarUrl = "https://www.gujaratsamachar.com/rss/city/bhavnagar"
    val gsBhujUrl = "https://www.gujaratsamachar.com/rss/city/bhuj"
    val gsKhedaUrl = "https://www.gujaratsamachar.com/rss/city/kheda-anand"
    val gsGandhinagarUrl = "https://www.gujaratsamachar.com/rss/city/gandhinagar"
    val gsNorthGujaratUrl = "https://www.gujaratsamachar.com/rss/city/north-gujarat"

    val dbEntertainmentUrl = "https://www.divyabhaskar.co.in/rss-feed/12042/"
    val dbBusinessUrl = "https://www.divyabhaskar.co.in/rss-feed/969/"
    val dbNationalUrl = "https://www.divyabhaskar.co.in/rss-feed/1037/"
    val dbInternationalUrl = "https://www.divyabhaskar.co.in/rss-feed/1038/"
    val dbSportsUrl = "https://www.divyabhaskar.co.in/rss-feed/970/"
    val dbNRGUrl = "https://www.divyabhaskar.co.in/rss-feed/7453/"

    val asHomeUrl = "https://gujarati.abplive.com/home/feed"
    val asGujaratUrl = "https://gujarati.abplive.com/news/gujarat/feed"
    val asBusinessUrl = "https://gujarati.abplive.com/business/feed"
    val asNationalUrl = "https://gujarati.abplive.com/news/india/feed"
    val asSportsUrl = "https://gujarati.abplive.com/sports/feed"
    val asAhmedabadUrl = "https://gujarati.abplive.com/news/ahmedabad/feed"
    val asSuratUrl = "https://gujarati.abplive.com/news/surat/feed"
    val asVadodaraUrl = "https://gujarati.abplive.com/news/vadodara/feed"
    val asRajkotUrl = "https://gujarati.abplive.com/news/rajkot/feed"
    val asGandhinagarUrl = "https://gujarati.abplive.com/news/gandhinagar/feed"
    val asMehsanaUrl = "https://gujarati.abplive.com/news/mehsana/feed"
    val asViseshUrl = "https://gujarati.abplive.com/asmita-vishesh/feed"
    val asWorldUrl = "https://gujarati.abplive.com/news/world/feed"
    val asGadgetsUrl = "https://gujarati.abplive.com/technology/gadgets/feed"
    val asLifestyleUrl = "https://gujarati.abplive.com/entertainment/lifestyle/feed"
    val asCrimeUrl = "https://gujarati.abplive.com/crime/feed"
    val asDharmaUrl = "https://gujarati.abplive.com/astro/dharam-jyotish/feed"
    val asBollywoodUrl = "https://gujarati.abplive.com/entertainment/feed"
    val asViralUrl = "https://gujarati.abplive.com/news/feed"
    val asAnandUrl = "https://gujarati.abplive.com/news/anand/feed"
    val asEventsUrl = "https://gujarati.abplive.com/events/feed"
    val asCovid19 = "https://gujarati.abplive.com/latest-news/covid-19/feed"

    val n18AjabGajabUrl = "https://gujarati.news18.com/rss/eye-catcher.xml"
    val n18CovidUrl = "https://gujarati.news18.com/rss/coronavirus-latest-news.xml"
    val n18CrimeUrl = "https://gujarati.news18.com/rss/crime.xml"
    val n18CricketUrl = "https://gujarati.news18.com/rss/cricket.xml"
    val n18GujaratUrl = "https://gujarati.news18.com/rss/gujarat.xml"
    val n18WorldUrl = "https://gujarati.news18.com/rss/world.xml"
    val n18CountryUrl = "https://gujarati.news18.com/rss/india.xml"
    val n18NationalInternationalUrl = "https://gujarati.news18.com/rss/national-international.xml"
    val n18DharmaUrl = "https://gujarati.news18.com/rss/dharm-bhakti.xml"
    val n18JobUrl = "https://gujarati.news18.com/rss/jobs.xml"
    val n18PressnoteUrl = "https://gujarati.news18.com/rss/press-release.xml"
    val n18IndoChinaUrl = "https://gujarati.news18.com/rss/india-china.xml"
    val n18EntertainmentUrl = "https://gujarati.news18.com/rss/entertainment.xml"
    val n18MoviesUrl = "https://gujarati.news18.com/rss/movies.xml"
    val n18MobileAndTechUrl = "https://gujarati.news18.com/rss/tech.xml"
    val n18LifestyleUrl = "https://gujarati.news18.com/rss/lifestyle.xml"
    val n18TradeUrl = "https://gujarati.news18.com/rss/business.xml"
}